In [43]:
import requests
import pandas as pd

In [44]:
URL = "https://www.freetogame.com/api/games"

In [66]:
try:
    response = requests.get(URL, timeout=5)
    response.raise_for_status()
except requests.exceptions.RequestException as e:

    print(f"Error: {e}")

In [67]:
data = response.json()

In [68]:
data

[{'id': 540,
  'title': 'Overwatch',
  'thumbnail': 'https://www.freetogame.com/g/540/thumbnail.jpg',
  'short_description': 'A hero-focused first-person team shooter from Blizzard Entertainment.',
  'game_url': 'https://www.freetogame.com/open/overwatch',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Activision Blizzard',
  'developer': 'Blizzard Entertainment',
  'release_date': '2022-10-04',
  'freetogame_profile_url': 'https://www.freetogame.com/overwatch'},
 {'id': 516,
  'title': 'PUBG: BATTLEGROUNDS',
  'thumbnail': 'https://www.freetogame.com/g/516/thumbnail.jpg',
  'short_description': 'Get into the action in one of the longest running battle royale games PUBG Battlegrounds.',
  'game_url': 'https://www.freetogame.com/open/pubg',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'KRAFTON, Inc.',
  'developer': 'KRAFTON, Inc.',
  'release_date': '2022-01-12',
  'freetogame_profile_url': 'https://www.freetogame.com/pubg'},
 {'id': 508,
  'title': 'Enlisted',
  'thumbnail': 'https://www.freetogame.com/g/508/thumbnail.jpg',
  'short_description': 'Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ',
  'game_url': 'https://www.freetogame.com/open/enlisted',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Gaijin Entertainment',
  'developer': 'Darkflow Software',
  'release_date': '2021-04-08',
  'freetogame_profile_url': 'https://www.freetogame.com/enlisted'},
 {'id': 642,
  'title': 'Neverness to Everness',
  'thumbnail': 'https://www.freetogame.com/g/642/thumbnail.jpg',
  'short_description': 'Neverness to Everness is a gacha game that blends some GTA-style play with team-based combat.',
  'game_url': 'https://www.freetogame.com/open/nte',
  'genre': 'RPG',
  'platform': 'PC (Windows)',
  'publisher': 'Perfect World Entertainment',
  'developer': 'Hotta Studio',
  'release_date': '2026-04-29',
  'freetogame_profile_url': 'https://www.freetogame.com/nte'},
 {'id': 604,
  'title': 'FragPunk',
  'thumbnail': 'https://www.freetogame.com/g/604/thumbnail.jpg',
  'short_description': 'A free-to-play 5v5 hero shooter that uses cards to modify matches.',
  'game_url': 'https://www.freetogame.com/open/fragpunk',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Bad Guitar Studio',
  'developer': 'Bad Guitar Studio',
  'release_date': '2025-03-06',
  'freetogame_profile_url': 'https://www.freetogame.com/fragpunk'},
 {'id': 590,
  'title': 'Throne And Liberty',
  'thumbnail': 'https://www.freetogame.com/g/590/thumbnail.jpg',
  'short_description': 'A free-to-play multi-platorm MMORPG from NCSoft and Amazon Games.',
  'game_url': 'https://www.freetogame.com/open/throne-and-liberty',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Amazon Games',
  'developer': 'NCSoft',
  'release_date': '2024-10-01',
  'freetogame_profile_url': 'https://www.freetogame.com/throne-and-liberty'},
 {'id': 523,
  'title': 'Fall Guys',
  'thumbnail': 'https://www.freetogame.com/g/523/thumbnail.jpg',
  'short_description': 'Play the most competitive massively multiplayer party royale game featuring beans ever for free on a variety of platforms. ',
  'game_url': 'https://www.freetogame.com/open/fall-guys',
  'genre': 'Battle Royale',
  'platform': 'PC (Windows)',
  'publisher': 'Mediatonic',
  'developer': 'Mediatonic',
  'release_date': '2020-08-04',
  'freetogame_profile_url': 'https://www.freetogame.com/fall-guys'},
 {'id': 340,
  'title': 'Game Of Thrones Winter Is Coming',
  'thumbnail': 'https://www.freetogame.com/g/340/thumbnail.jpg',
  'short_description': 'A free-to-play browser-based RTS based on the George R.R. Martin novels and popular HBO series.',
  'game_url': 'https://www.freetogame.com/open/game-of-thrones-winter-is-coming',
  'genre': 'Strategy',
  'platform': 'Web Browser',
  'publisher': 'GTArcade',
  'developer': 'YOOZOO Games ',
  'release_date': '2019-11-14',
  'freetogame_profile_url': 'https://www.freetogame.com/game-of-thrones-winter-is-coming'},
 {'id': 347,
  'title': 'Elvenar',
  'thumbnail': 'https://www.freetogame.com/g/347/thumbnail.jpg',
  'short_description': 'A browser based city-building strategy MMO set in the fantasy world of Elvenar.',
  'game_url': 'https://www.freetogame.com/open/elvenar',
  'genre': 'Strategy',
  'platform': 'Web Browser',
  'publisher': 'InnoGames',
  'developer': 'InnoGames',
  'release_date': '2015-04-08',
  'freetogame_profile_url': 'https://www.freetogame.com/elvenar'},
 {'id': 11,
  'title': 'Neverwinter',
  'thumbnail': 'https://www.freetogame.com/g/11/thumbnail.jpg',
  'short_description': 'A free-to-play 3D action MMORPG based on the acclaimed Dungeons & Dragons fantasy roleplaying game. ',
  'game_url': 'https://www.freetogame.com/open/neverwinter',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Perfect World Entertainment',
  'developer': 'Cryptic Studios',
  'release_date': '2013-12-06',
  'freetogame_profile_url': 'https://www.freetogame.com/neverwinter'},
 {'id': 628,
  'title': 'World of Sea Battle',
  'thumbnail': 'https://www.freetogame.com/g/628/thumbnail.jpg',
  'short_description': 'A free-to-play historical open-sea MMORPG.',
  'game_url': 'https://www.freetogame.com/open/world-of-sea-battle',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Thera Interactive',
  'developer': 'Thera Interactive',
  'release_date': '2025-10-21',
  'freetogame_profile_url': 'https://www.freetogame.com/world-of-sea-battle'},
 {'id': 517,
  'title': 'Lost Ark',
  'thumbnail': 'https://www.freetogame.com/g/517/thumbnail.jpg',
  'short_description': 'Smilegate’s free-to-play multiplayer ARPG is a massive adventure filled with lands waiting to be explored, people waiting to be met, and an ancient evil waiting to be destroyed.',
  'game_url': 'https://www.freetogame.com/open/lost-ark',
  'genre': 'ARPG',
  'platform': 'PC (Windows)',
  'publisher': 'Amazon Games',
  'developer': 'Smilegate RPG',
  'release_date': '2022-02-11',
  'freetogame_profile_url': 'https://www.freetogame.com/lost-ark'},
 {'id': 475,
  'title': 'Genshin Impact',
  'thumbnail': 'https://www.freetogame.com/g/475/thumbnail.jpg',
  'short_description': 'If you’ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you’re going to want to check out miHoYo’s Genshin Impact.',
  'game_url': 'https://www.freetogame.com/open/genshin-impact',
  'genre': 'Action RPG',
  'platform': 'PC (Windows)',
  'publisher': 'miHoYo',
  'developer': 'miHoYo',
  'release_date': '2020-09-28',
  'freetogame_profile_url': 'https://www.freetogame.com/genshin-impact'},
 {'id': 620,
  'title': 'Hero Wars: Dominion Era',
  'thumbnail': 'https://www.freetogame.com/g/620/thumbnail.jpg',
  'short_description': 'A free-to-play fantasy MMORPG where players assemble teams of heroes to battle against powerful enemies.',
  'game_url': 'https://www.freetogame.com/open/hero-wars',
  'genre': 'MMORPG',
  'platform': 'Web Browser',
  'publisher': 'Nexters',
  'developer': 'Nexters',
  'release_date': '2016-10-01',
  'freetogame_profile_url': 'https://www.freetogame.com/hero-wars'},
 {'id': 9,
  'title': 'World of Warships',
  'thumbnail': 'https://www.freetogame.com/g/9/thumbnail.jpg',
  'short_description': 'A 3D free to play naval action-themed MMO from the creators of World of Tanks! ',
  'game_url': 'https://www.freetogame.com/open/world-of-warships',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Wargaming',
  'developer': 'Wargaming',
  'release_date': '2015-07-02',
  'freetogame_profile_url': 'https://www.freetogame.com/world-of-warships'},
 {'id': 2,
  'title': 'World of Tanks',
  'thumbnail': 'https://www.freetogame.com/g/2/thumbnail2.jpg',
  'short_description': 'If you like blowing up tanks, with a quick and intense game style you will love this game!',
  'game_url': 'https://www.freetogame.com/open/world-of-tanks',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Wargaming',
  'developer': 'Wargaming',
  'release_date': '2011-04-12',
  'freetogame_profile_url': 'https://www.freetogame.com/world-of-tanks'},
 {'id': 521,
  'title': 'Diablo Immortal',
  'thumbnail': 'https://www.freetogame.com/g/521/thumbnail.jpg',
  'short_description': 'Built for mobile and also released on PC, Diablo Immortal fills in the gaps between Diablo II and III in an MMOARPG environment.',
  'game_url': 'https://www.freetogame.com/open/diablo-immortal',
  'genre': 'MMOARPG',
  'platform': 'PC (Windows)',
  'publisher': 'Blizzard Entertainment',
  'developer': 'Blizzard Entertainment',
  'release_date': '2022-06-02',
  'freetogame_profile_url': 'https://www.freetogame.com/diablo-immortal'},
 {'id': 511,
  'title': 'Phantasy Star Online 2 New Genesis',
  'thumbnail': 'https://www.freetogame.com/g/511/thumbnail.jpg',
  'short_description': 'The legacy of Phantasy Star Online 2 continues a thousand years later!',
  'game_url': 'https://www.freetogame.com/open/pso2-new-genesis',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Sega',
  'developer': 'Sega',
  'release_date': '2021-06-09',
  'freetogame_profile_url': 'https://www.freetogame.com/pso2-new-genesis'},
 {'id': 5,
  'title': 'Crossout',
  'thumbnail': 'https://www.freetogame.com/g/5/thumbnail.jpg',
  'short_description': 'A post-apocalyptic MMO vehicle combat game! ',
  'game_url': 'https://www.freetogame.com/open/crossout',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Targem',
  'developer': 'Gaijin',
  'release_date': '2017-05-30',
  'freetogame_profile_url': 'https://www.freetogame.com/crossout'},
 {'id': 12,
  'title': 'War Thunder',
  'thumbnail': 'https://www.freetogame.com/g/12/thumbnail.jpg',
  'short_description': 'A MMO shooter that puts you in command of hundreds of the finest combat vehicles of World War II.',
  'game_url': 'https://www.freetogame.com/open/war-thunder',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Gaijin Entertainment',
  'developer': 'Gaijin Entertainment',
  'release_date': '2013-08-15',
  'freetogame_profile_url': 'https://www.freetogame.com/war-thunder'},
 {'id': 624,
  'title': 'Battlefield REDSEC',
  'thumbnail': 'https://www.freetogame.com/g/624/thumbnail.jpg',
  'short_description': 'A free-to-play battle royale game built with Battlefield DNA.',
  'game_url': 'https://www.freetogame.com/open/battlefield-redsec',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Electronic Arts',
  'developer': 'Battlefield Studios',
  'release_date': '2025-10-28',
  'freetogame_profile_url': 'https://www.freetogame.com/battlefield-redsec'},
 {'id': 641,
  'title': 'Foundation: Galactic Frontier',
  'thumbnail': 'https://www.freetogame.com/g/641/thumbnail.jpg',
  'short_description': 'Isaac Asimov’s series brought to life in a massive real-time strategy RPG featuring crew management and galactic warfare.',
  'game_url': 'https://www.freetogame.com/open/foundation-galactic-frontier',
  'genre': 'Strategy',
  'platform': 'PC (Windows)',
  'publisher': 'FunPlus International',
  'developer': 'FunPlus International',
  'release_date': '2025-10-21',
  'freetogame_profile_url': 'https://www.freetogame.com/foundation-galactic-frontier'},
 {'id': 599,
  'title': 'Marvel Rivals',
  'thumbnail': 'https://www.freetogame.com/g/599/thumbnail.jpg',
  'short_description': 'A free-to-play superhero team shooter from NetEase.',
  'game_url': 'https://www.freetogame.com/open/marvel-rivals',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'NetEase',
  'developer': 'NetEase',
  'release_date': '2024-12-06',
  'freetogame_profile_url': 'https://www.freetogame.com/marvel-rivals'},
 {'id': 640,
  'title': 'Project Entropy',
  'thumbnail': 'https://www.freetogame.com/g/640/thumbnail.jpg',
  'short_description': 'Project Entropy drops you into a living sci-fi MMO universe!',
  'game_url': 'https://www.freetogame.com/open/project-entropy',
  'genre': 'Strategy',
  'platform': 'PC (Windows)',
  'publisher': 'FunPlus International',
  'developer': 'FunPlus International',
  'release_date': '2024-04-17',
  'freetogame_profile_url': 'https://www.freetogame.com/project-entropy'},
 {'id': 560,
  'title': 'Palia',
  'thumbnail': 'https://www.freetogame.com/g/560/thumbnail.jpg',
  'short_description': 'A cozy MMO with homebuilding and some adventure.',
  'game_url': 'https://www.freetogame.com/open/palia',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Singularity Six',
  'developer': 'Singularity Six',
  'release_date': '2023-08-10',
  'freetogame_profile_url': 'https://www.freetogame.com/palia'},
 {'id': 458,
  'title': "League of Angels - Heaven's Fury",
  'thumbnail': 'https://www.freetogame.com/g/458/thumbnail.jpg',
  'short_description': 'A free-to-play, browser-based fantasy online action RPG based loosely on Western mythology!',
  'game_url': 'https://www.freetogame.com/open/league-of-angels-heavens-fury',
  'genre': 'MMORPG',
  'platform': 'Web Browser',
  'publisher': 'Gtarcade',
  'developer': 'Yoozoo Games',
  'release_date': '2020-01-09',
  'freetogame_profile_url': 'https://www.freetogame.com/league-of-angels-heavens-fury'},
 {'id': 345,
  'title': 'Forge of Empires',
  'thumbnail': 'https://www.freetogame.com/g/345/thumbnail.jpg',
  'short_description': 'A free to play 2D browser-based online strategy game, become the leader and raise your city.',
  'game_url': 'https://www.freetogame.com/open/forge-of-empires',
  'genre': 'Strategy',
  'platform': 'Web Browser',
  'publisher': 'InnoGames',
  'developer': 'InnoGames',
  'release_date': '2012-04-17',
  'freetogame_profile_url': 'https://www.freetogame.com/forge-of-empires'},
 {'id': 14,
  'title': 'Star Trek Online',
  'thumbnail': 'https://www.freetogame.com/g/14/thumbnail.jpg',
  'short_description': 'A free-to-play, 3D, Sci-Fi MMORPG based on the popular Star Trek series.',
  'game_url': 'https://www.freetogame.com/open/star-trek-online',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Perfect World Entertainment',
  'developer': ' Cryptic Studios',
  'release_date': '2010-02-02',
  'freetogame_profile_url': 'https://www.freetogame.com/star-trek-online'},
 {'id': 626,
  'title': 'Where Winds Meet',
  'thumbnail': 'https://www.freetogame.com/g/626/thumbnail.jpg',
  'short_description': 'A free-to-play open-world ARPG set in tenth-century China.',
  'game_url': 'https://www.freetogame.com/open/where-winds-meet',
  'genre': 'RPG',
  'platform': 'PC (Windows)',
  'publisher': 'Everstone Studio',
  'developer': 'NetEase Games',
  'release_date': '2025-11-14',
  'freetogame_profile_url': 'https://www.freetogame.com/where-winds-meet'},
 {'id': 595,
  'title': 'Brighter Shores',
  'thumbnail': 'https://www.freetogame.com/g/595/thumbnail.jpg',
  'short_description': "A point-and-click MMORPG from RuneScape's creator, Andrew Gower.",
  'game_url': 'https://www.freetogame.com/open/brighter-shores',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'Fen Research LTD',
  'developer': 'Fen Research LTD',
  'release_date': '2024-11-06',
  'freetogame_profile_url': 'https://www.freetogame.com/brighter-shores'},
 {'id': 515,
  'title': 'Halo Infinite',
  'thumbnail': 'https://www.freetogame.com/g/515/thumbnail.jpg',
  'short_description': 'For the first time ever, a free-to-play Halo experience is available in the form of Halo Infinite’s multiplayer.',
  'game_url': 'https://www.freetogame.com/open/halo-infinite',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Xbox Game Studios',
  'developer': '343 Industries',
  'release_date': '2021-11-15',
  'freetogame_profile_url': 'https://www.freetogame.com/halo-infinite'},
 {'id': 466,
  'title': 'Valorant',
  'thumbnail': 'https://www.freetogame.com/g/466/thumbnail.jpg',
  'short_description': 'Test your mettle in Riot Games’ character-based FPS shooter Valorant.',
  'game_url': 'https://www.freetogame.com/open/valorant',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Riot Games',
  'developer': 'Riot Games',
  'release_date': '2020-06-02',
  'freetogame_profile_url': 'https://www.freetogame.com/valorant'},
 {'id': 467,
  'title': 'Phantasy Star Online 2',
  'thumbnail': 'https://www.freetogame.com/g/467/thumbnail.jpg',
  'short_description': 'Welcome to ARKS, and elite task force searching dangerous planets for the corrupted Falspawn in Phantasy Star 2 Online, Sega’s popular, free-to-play sci-fi MMORPG.',
  'game_url': 'https://www.freetogame.com/open/pso2',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'SEGA',
  'developer': 'SEGA',
  'release_date': '2020-05-27',
  'freetogame_profile_url': 'https://www.freetogame.com/pso2'},
 {'id': 452,
  'title': 'Call of Duty: Warzone',
  'thumbnail': 'https://www.freetogame.com/g/452/thumbnail.jpg',
  'short_description': 'A standalone free-to-play battle royale and modes accessible via Call of Duty: Modern Warfare.',
  'game_url': 'https://www.freetogame.com/open/call-of-duty-warzone',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Activision',
  'developer': 'Infinity Ward',
  'release_date': '2020-03-10',
  'freetogame_profile_url': 'https://www.freetogame.com/call-of-duty-warzone'},
 {'id': 21,
  'title': 'Destiny 2',
  'thumbnail': 'https://www.freetogame.com/g/21/thumbnail.jpg',
  'short_description': 'A free-to-play multiplayer Sci-Fi MMOFPS from Bungie.',
  'game_url': 'https://www.freetogame.com/open/destiny-2',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Bungie',
  'developer': 'Bungie',
  'release_date': '2019-10-01',
  'freetogame_profile_url': 'https://www.freetogame.com/destiny-2'},
 {'id': 23,
  'title': 'Apex Legends',
  'thumbnail': 'https://www.freetogame.com/g/23/thumbnail.jpg',
  'short_description': 'A free-to-play strategic battle royale game featuring 60-player matches and team-based play. ',
  'game_url': 'https://www.freetogame.com/open/apex-legends',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Electronic Arts',
  'developer': 'Electronic Arts',
  'release_date': '2019-02-04',
  'freetogame_profile_url': 'https://www.freetogame.com/apex-legends'},
 {'id': 57,
  'title': 'Fortnite',
  'thumbnail': 'https://www.freetogame.com/g/57/thumbnail.jpg',
  'short_description': "A free-to-play, standalone mode of Epic Game's Fortnite. ",
  'game_url': 'https://www.freetogame.com/open/fortnite-battle-royale',
  'genre': 'Shooter',
  'platform': 'PC (Windows)',
  'publisher': 'Epic Games',
  'developer': 'Epic Games',
  'release_date': '2017-09-26',
  'freetogame_profile_url': 'https://www.freetogame.com/fortnite-battle-royale'},
 {'id': 6,
  'title': 'Blade and Soul',
  'thumbnail': 'https://www.freetogame.com/g/6/thumbnail.jpg',
  'short_description': 'A free-to-play martial arts MMORPG that tasks players with learning combination attacks.',
  'game_url': 'https://www.freetogame.com/open/blade-and-soul',
  'genre': 'MMORPG',
  'platform': 'PC (Windows)',
  'publisher': 'NCSoft',
  'developer': 'NCSoft',
  'release_date': '2016-01-19',
  'freetogame_profile_url': 'https://www.freetogame.com/blade-and-soul'},
 {'id': 212,
  'title': 'Brawlhalla',
  'thumbnail': 'https://www.freetogame.com/g/212/thumbnail.jpg',
  'short_description': 'A free-to-play 2D platform fighter inspired by the Smash Bros.',
  'game_url': 'https://www.freetogame.com/open/brawlhalla',
  'genre': 'Fighting',
  'platform': 'PC (Windows)',
  'publisher': 'Blue Mammoth Games',
  'developer': 'Blue Mammoth Games',
  'release_date': '2015-11-03',
  'freetogame_profile_url': 'https://www.freetogame.com/brawlhalla'},
 {'id': 8,
  'title': 'Trove',
  'thumbnail': 'https://www.freetogame.com/g/8/thumbnail.jpg',
  'short_description': 'A free to play Sandbox massively multiplayer online role-playing game! ',

In [69]:
json_data = pd.json_normalize(data)

In [70]:
filtered_json_data = json_data[['title', 'genre', 'platform', 'publisher', 'release_date', 'game_url']]
json_data

,id,title,thumbnail,short_description,game_url,genre,platform,publisher,developer,release_date,freetogame_profile_url
0,540,Overwatch,https://www.freetogame.com/g/540/thumbnail.jpg,A hero-focused first-person team shooter from ...,https://www.freetogame.com/open/overwatch,Shooter,PC (Windows),Activision Blizzard,Blizzard Entertainment,2022-10-04,https://www.freetogame.com/overwatch
1,516,PUBG: BATTLEGROUNDS,https://www.freetogame.com/g/516/thumbnail.jpg,Get into the action in one of the longest runn...,https://www.freetogame.com/open/pubg,Shooter,PC (Windows),"KRAFTON, Inc.","KRAFTON, Inc.",2022-01-12,https://www.freetogame.com/pubg
2,508,Enlisted,https://www.freetogame.com/g/508/thumbnail.jpg,Get ready to command your own World War II mil...,https://www.freetogame.com/open/enlisted,Shooter,PC (Windows),Gaijin Entertainment,Darkflow Software,2021-04-08,https://www.freetogame.com/enlisted
3,642,Neverness to Everness,https://www.freetogame.com/g/642/thumbnail.jpg,Neverness to Everness is a gacha game that ble...,https://www.freetogame.com/open/nte,RPG,PC (Windows),Perfect World Entertainment,Hotta Studio,2026-04-29,https://www.freetogame.com/nte
4,604,FragPunk,https://www.freetogame.com/g/604/thumbnail.jpg,A free-to-play 5v5 hero shooter that uses card...,https://www.freetogame.com/open/fragpunk,Shooter,PC (Windows),Bad Guitar Studio,Bad Guitar Studio,2025-03-06,https://www.freetogame.com/fragpunk
...,...,...,...,...,...,...,...,...,...,...,...
404,335,Ragnarok Online,https://www.freetogame.com/g/335/thumbnail.jpg,"A popular fantasy MMORPG, back to the golden a...",https://www.freetogame.com/open/ragnarok-online,MMORPG,PC (Windows),Gravity Interactive,Gravity Interactive,2003-06-01,https://www.freetogame.com/ragnarok-online
405,17,Entropia Universe,https://www.freetogame.com/g/17/thumbnail.jpg,A 3D MMO Multi Virtual World Real Cash Economy...,https://www.freetogame.com/open/entropia-universe,MMORPG,PC (Windows),MindArk,MindArk,2003-01-30,https://www.freetogame.com/entropia-universe
406,432,Habbo,https://www.freetogame.com/g/432/thumbnail.jpg,One of the largest and most popular Social MMO.,https://www.freetogame.com/open/habbo,Social,Web Browser,Sulake Corporation,Sulake Corporation,2001-09-26,https://www.freetogame.com/habbo
407,336,Anarchy Online,https://www.freetogame.com/g/336/thumbnail.jpg,A free to play Sci-Fi MMO that has withstood t...,https://www.freetogame.com/open/anarchy-online,MMORPG,PC (Windows),Funcom,Funcom,2001-06-27,https://www.freetogame.com/anarchy-online
408,251,The Lord of the Rings Online,https://www.freetogame.com/g/251/thumbnail.jpg,A free to play MMORPG set in the world of J.R....,https://www.freetogame.com/open/lotro,MMORPG,PC (Windows),Warner Bros. Interactive Entertainment,"Turbine, Inc.",2001-04-24,https://www.freetogame.com/lotro

In [72]:
filtered_json_data[filtered_json_data["genre"] == 'Shooter']

,title,genre,platform,publisher,release_date,game_url
0,Overwatch,Shooter,PC (Windows),Activision Blizzard,2022-10-04,https://www.freetogame.com/open/overwatch
1,PUBG: BATTLEGROUNDS,Shooter,PC (Windows),"KRAFTON, Inc.",2022-01-12,https://www.freetogame.com/open/pubg
2,Enlisted,Shooter,PC (Windows),Gaijin Entertainment,2021-04-08,https://www.freetogame.com/open/enlisted
4,FragPunk,Shooter,PC (Windows),Bad Guitar Studio,2025-03-06,https://www.freetogame.com/open/fragpunk
14,World of Warships,Shooter,PC (Windows),Wargaming,2015-07-02,https://www.freetogame.com/open/world-of-warships
...,...,...,...,...,...,...
368,Ace Online,Shooter,PC (Windows),Suba Games,2008-08-29,https://www.freetogame.com/open/ace-online
375,Team Fortress 2,Shooter,PC (Windows),Valve,2007-10-10,https://www.freetogame.com/open/team-fortress-2
379,Crossfire,Shooter,PC (Windows),Neowiz Games,2007-05-03,https://www.freetogame.com/open/crossfire
380,Teeworlds,Shooter,PC (Windows),Teeworlds Team,2007-05-27,https://www.freetogame.com/open/teeworlds
384,Dark Orbit Reloaded,Shooter,Web Browser,Bigpoint,2006-12-11,https://www.freetogame.com/open/darkorbit