In [33]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [34]:
heart_df = pd.read_csv("./datasets/heart.csv")
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [35]:
X = heart_df.drop(columns=["target"])
Y = heart_df["target"]

X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [36]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, random_state=42)

In [40]:
scaler = StandardScaler()

In [41]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [51]:
def knn_training_evaluation(n: int = 3):
    knn_classifier = KNeighborsClassifier(n_neighbors=n)

    knn_classifier.fit(X_train_scaled, y_train)

    y_pred = knn_classifier.predict(X_test_scaled)

    print(f"Recall score: {recall_score(y_test, y_pred)}")
    print(f"Accuracy score: {accuracy_score(y_test, y_pred)}")
    print(f"Precision score: {precision_score(y_test, y_pred)}")

In [52]:
knn_training_evaluation(3)

Recall score: 0.84375
Accuracy score: 0.8688524590163934
Precision score: 0.9

In [54]:
knn_training_evaluation(5)

Recall score: 0.90625
Accuracy score: 0.9016393442622951
Precision score: 0.90625

In [55]:
knn_training_evaluation(10)

Recall score: 0.875
Accuracy score: 0.8688524590163934
Precision score: 0.875